print('Hello, World!')
print('What is your name?')
print()
myName = input()
print()
print('Nice to meet you, ' + myName)
print()
print('How old are you, ' + myName + '?')
print()
myAge = input()
print()
print('You will be ' + str(int(myAge) + 5) + ' in next Five years.')
print()
print('Write ' + str(int(50)) + ' letters about your self.')
print()
mySelf = input()
print()
print('There are ' + str(len(mySelf)) + ' letters that you wrote in the earlier para.')
print()
print('Honoured to talk with you Mr. ' + myName + ', Thanks for giving me some time.')
